apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-nginx
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: platform@${ARGOCD_ENV_DNS_DOMAIN}
    privateKeySecretRef:
      name: letsencrypt-staging-nginx

    solvers:
      - http01:
          ingress:
            class: nginx
