apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-op
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.3
    helm:
      parameters:
        - name: resources.requests.memory
          value: "64Mi"
        - name: resources.limits.memory
          value: "128Mi"
        - name: resources.requests.cpu
          value: "60m"
        - name: resources.limits.cpu
          value: "120m"
        - name: podDisruptionBudget.enabled
          value: "true"

      # values: |
      #   serviceAccount:
      #     annotations:
      #       iam.gke.io/gcp-service-account: secret-manager-reader@${ARGOCD_ENV_PROJECT}.iam.gserviceaccount.com

  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
