apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  sources:
    - chart: kafka
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 24.0.14
      # https://github.com/bitnami/charts/tree/main/bitnami/kafka

      helm:
        values: |
          kraft:
            enabled: true
            clusterId: GTxB5josEfsini5mBw33W7
          listeners:
            client:
              containerPort: 9092
              protocol: SASL_SSL # SASL_PLAINTEXT
            controller:
              containerPort: 9093
              protocol: SASL_SSL # SASL_PLAINTEXT
            interbroker:
              containerPort: 9094
              protocol: SASL_PLAINTEXT # SASL_SSL
            external:
              containerPort: 9095
              protocol: SASL_PLAINTEXT # SASL_SSL
          
          # https://github.com/bitnami/charts/issues/17497#issuecomment-1625089275
          # At the moment, our Kafka chart does not support SCRAM mechanism yet.
          # SCRAM support in KRaft mode has been recently added in the latest version 3.5 and we are currently working on adding support for it.
          # As a temporary fix for your issue, could you please try setting auth.sasl.mechanisms=plain in the chart values?
          sasl:
            interBrokerMechanism: PLAIN # SCRAM-SHA-256
            controllerMechanism: PLAIN # SCRAM-SHA-256
            interbroker:
              user: inter_broker_user
              # password: password
            controller:
              user: controller_user
              # password: password
            client:
              users:
                - admin
                - user
              passwords: 
                - password
                - password
            # existingSecret: kafka-passwords


          # https://github.com/bitnami/charts/tree/main/bitnami/kafka#enable-security-for-kafka-and-zookeeper
          # https://docs.bitnami.com/kubernetes/infrastructure/kafka/administration/enable-tls/

          tls:
            type: PEM
            pemChainIncluded: false
            autoGenerated: true
            # existingSecret: kafka-passwords
            # passwordsSecret: password
            # sslClientAuth: none

          # extraDeploy:
          #   - apiVersion: v1
          #     kind: Secret
          #     metadata:
          #       name: kafka-passwords
          #       namespace: kafka

          #     data:
          #       key-password: cGFzc3dvcmQ=
          #       keystore-password: cGFzc3dvcmQ=
          #       truststore-password: cGFzc3dvcmQ=
          #       client-passwords: cGFzc3dvcmQscGFzc3dvcmQscGFzc3dvcmQscGFzc3dvcmQ=
          #       inter-broker-password: cGFzc3dvcmQ= 
          #       controller-password: cGFzc3dvcmQ=
          #     type: Opaque


          controller:
            replicaCount: 3
            # resources:
            #   requests:
            #     memory: "2.5Gi"
            #     cpu: "1"
            #   limits:
            #     memory: "2.5Gi"
            #     cpu: "1"
          persistence:
            # storageClass: auto-resize
            size: 8Gi
          metrics:
            kafka:
              enabled: true
              # extraFlags:
              resources:
                requests:
                  memory: "150Mi"
                  cpu: "0.1"
                limits:
                  memory: "150Mi"
                  cpu: "0.1"

            # serviceMonitor:
            #   enabled: true
            #   labels:
            #     release: observability-kube-prometheus

    - chart: console
      repoURL: https://helm.conduktor.io
      targetRevision: 1.0.1
      # https://github.com/conduktor/conduktor-public-charts/tree/main/charts/console
      helm:
        values: |
          fullnameOverride: conduktor-console
          config:
            organization:
              name: my-org
            admin:
              email: admin@conduktor.io
              password: password
            database:
              host: conduktor-postgres
              name: conduktor
              username: admin
              password: password
          ingress:
            enabled: true
            ingressClassName: nginx
            hostname: kafka.local.com.br

    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 12.8.3
      # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
      helm:
        values: |
          fullnameOverride: conduktor-postgres
          auth:
            postgresPassword: password
            database: conduktor
            username: admin
            password: password
  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kafka
