apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  sources:
    - chart: kafka
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 24.0.14
      # https://github.com/bitnami/charts/tree/main/bitnami/kafka
      helm:
        values: |
          kraft:
            enabled: true
            clusterId: GTxB5josEfsini5mBw33W7
          listeners:
            client: 
              protocol: SASL_SSL
            controller: 
              protocol: SASL_SSL
            interbroker: 
              protocol: SASL_SSL
            external: 
              protocol: SASL_SSL
          tls:
            autoGenerated: true
          
          # NOTE: KRaft <= 3.4 does not yet support SCRAM mechanisms, so this list will be automatically reduced to only PLAIN SASL mechanism.
          sasl:
            interBrokerMechanism: SCRAM-SHA-256 # SCRAM-SHA-256
            controllerMechanism: SCRAM-SHA-256 # SCRAM-SHA-256
            interbroker:
              user: inter_broker_user
              password: e6QGw1R6si
            controller:
              user: controller_user
              password: 9YbCuBKtk6
            client:
              users:
                - admin
                - user
              passwords: 
                - password
                - password
          controller:
            replicaCount: 3
            # resources:
            #   requests:
            #     memory: "2.5Gi"
            #     cpu: "1"
            #   limits:
            #     memory: "2.5Gi"
            #     cpu: "1"
          persistence:
            # storageClass: auto-resize
            size: 8Gi
          metrics:
            kafka:
              enabled: true
              # extraFlags:
              resources:
                requests:
                  memory: "150Mi"
                  cpu: "0.1"
                limits:
                  memory: "150Mi"
                  cpu: "0.1"

            # serviceMonitor:
            #   enabled: true
            #   labels:
            #     release: observability-kube-prometheus

    - chart: console
      repoURL: https://helm.conduktor.io
      targetRevision: 1.0.1
      # https://github.com/conduktor/conduktor-public-charts/tree/main/charts/console
      helm:
        values: |
          fullnameOverride: conduktor-console
          config:
            organization:
              name: my-org
            admin:
              email: admin@conduktor.io
              password: password
            database:
              host: conduktor-postgres
              name: conduktor
              username: admin
              password: password
          ingress:
            enabled: true
            ingressClassName: nginx
            hostname: kafka.local.com.br

    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 12.8.3
      # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
      helm:
        values: |
          fullnameOverride: conduktor-postgres
          auth:
            postgresPassword: password
            database: conduktor
            username: admin
            password: password
  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kafka
