# https://docs.redpanda.com/docs/reference/crd/#redpanda

apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef:
    timeout: 1m0s
  
  clusterSpec:
    external:
      domain: redpanda.local
    statefulset:
      PodAntiAffinity:
        type: custom
        custom:
          rule: ""
      initContainers:
        setDataDirOwnership:
          enabled: true
