# https://docs.redpanda.com/docs/reference/crd/#redpanda

apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef:
    timeout: 60
  clusterSpec:
    external:
      domain: redpanda.local
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true