apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-controller
  namespace: argocd

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  source:
    chart: redpanda
    repoURL: https://charts.redpanda.com
    targetRevision: 5.1.3

  destination:
    server: "https://kubernetes.default.svc"
    namespace: redpanda