apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  source:
    chart: redpanda
    repoURL: https://charts.redpanda.com
    targetRevision: 5.1.3
    # https://github.com/redpanda-data/helm-charts/tree/main/charts/redpanda
    helm:
      values: |
        console:
          configmap:
            create: false
          secret:
            create: false
          deployment:
            create: true
        statefulset:
          replicas: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redpanda