apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-controller
  namespace: argocd

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  sources:
    - chart: operator
      repoURL: https://charts.redpanda.com
      targetRevision: 0.3.11

    # https://docs.redpanda.com/docs/reference/redpanda-operator/crd/
    - repoURL: https://github.com/Jojoooo1/kustomization-crds.git # v23.2.5
      targetRevision: main
      path: redpanda

  destination:
    server: "https://kubernetes.default.svc"
    namespace: redpanda