apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-external-secrets-op-helm
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true

  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.8

    # https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
    helm:
      valuesObject:
        fullnameOverride: external-secrets

        # resources:
        #   requests:
        #     cpu: 60m
        #     memory: 64Mi
        #   limits:
        #     cpu: 120m
        #     memory: 128Mi

        # podDisruptionBudget:
        #   enabled: true

        servicemonitor:
          enabled: false # true
          labels:
            prometheus.io/scrap-with: kube-prometheus-stack
    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
