apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-helm
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true

  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.10.0

    # https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
    helm:
      valuesObject:
        fullnameOverride: external-secrets
        installCRDs: true
        # resources:
        #   requests:
        #     cpu: 75m
        #     memory: 64Mi
        #   limits:
        #     cpu: 75m
        #     memory: 64Mi
        # podDisruptionBudget:
        #   enabled: true
        
        servicemonitor:
          enabled: true # true
          labels:
            prometheus.io/scrap-with: kube-prometheus-stack

        # Use workload identity to give the external-secrets pod access to the GCP Secret Manager API.
        # serviceAccount:
        #   annotations: 
        #     iam.gke.io/gcp-service-account: external-secrets@${ARGOCD_ENV_PROJECT}.iam.gserviceaccount.com
    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
