apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-cluster
  namespace: argocd

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  sources:
    - repoURL: https://github.com/Jojoooo1/argo-deploy-applications-infra.git
      targetRevision: main
      path: overlays/local/applications-infra/redpanda-cluster
    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redpanda