apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-op
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true

  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.4

    # https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
    helm:
      valuesObject:
        resources:
          requests:
            cpu: 60m
            memory: 64Mi
          limits:
            cpu: 120m
            memory: 128Mi
        podDisruptionBudget:
          enabled: true

        # serviceAccount:
        #   annotations: 
        #     iam.gke.io/gcp-service-account: secret-manager-reader@${ARGOCD_ENV_PROJECT}.iam.gserviceaccount.com
    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
