apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  sources:
    - chart: kafka
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 25.1.5

      # https://docs.confluent.io/platform/current/kafka/deployment.html
      # https://github.com/bitnami/charts/tree/main/bitnami/kafka
      helm:
        valuesObject:
          kraft:
            enabled: true
            clusterId: GTxB5josEfsini5mBw33W7
          listeners:
            client:
              containerPort: 9092
              protocol: SASL_SSL
            external:
              containerPort: 9095
              protocol: SASL_SSL
            controller:
              containerPort: 9093
              protocol: SASL_PLAINTEXT
            interbroker:
              containerPort: 9094
              protocol: SASL_PLAINTEXT
          
          # https://github.com/bitnami/charts/issues/17497#issuecomment-1625089275
          # SCRAM support in KRaft mode has been recently added in the latest version 3.5 and we are currently working on adding support for it.
          sasl:
            interBrokerMechanism: PLAIN # SCRAM-SHA-256
            controllerMechanism: PLAIN # SCRAM-SHA-256
            interbroker:
              user: inter_broker_user
              # password: ""
            controller:
              user: controller_user
              # password: ""
            client:
              users:
                - admin
                - user
              passwords: 
                - password
                - password
            existingSecret: kfk-passwords

          tls:
            type: PEM
            pemChainIncluded: false
            autoGenerated: true
            existingSecret: kfka-tls
            sslClientAuth: required

          extraDeploy:
            - apiVersion: v1
              kind: Secret
              metadata:
                name: kfk-passwords
                namespace: kafka
                # system-user-password  is used for kafka exporter
                # client-passwords is used for sasl
              data:
                client-passwords: cGFzc3dvcmQscGFzc3dvcmQscGFzc3dvcmQscGFzc3dvcmQ=
                system-user-password: cGFzc3dvcmQ=
                inter-broker-password: ZDk1dTVOcGtCeA==
                controller-password: WUgxTEJkakRmeA==
              type: Opaque

            - apiVersion: v1
              kind: Secret
              metadata:
                name: kfka-tls
                namespace: kafka
              data:
                kafka-ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lRT1hiOG0vUHZMa2I2RENGOEFWNlo2akFOQmdrcWhraUc5dzBCQVFzRkFEQVQKTVJFd0R3WURWUVFERXdocllXWnJZUzFqWVRBZUZ3MHlNekE0TWpNeE1ERTJNakJhRncweU5EQTRNakl4TURFMgpNakJhTUJNeEVUQVBCZ05WQkFNVENHdGhabXRoTFdOaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTB0alRkaWpmR2RwTlUwSzRCVGdibGhsakFVM3VrWFkyUXplWTUxOW9ScFVldlhNbXFzWXgKSlVNQk1tMjFtYzZrSVluU2x6S0dsRWU0Nlorc2UwN2oyeE5DSy9pTXd1enJ4VDNOM1dlMEFGMElzRUp4a2krUQpFT1NzcFhFdXdoLzdIekFKT1AzRktOeGxyTHJKT2dwcjBZcE00bjZ2YjRvUUYrWTF3clR2ZzYzNWc5cUltOFZyCnJrdUZkMTErR0xRWkFOelo3SER4cGJhRjJqVzJvWWVFNXQ1Y1lhNWVCbVNEZjcxUmhYRVJ6ek5IQUhhUkV1MEYKd3JUeUZzMG1Eb3J5YWNhS2JEb2tXdWVsMkQxMjIrczBLN3NoaGovZXFKaW1kdDdGZUc3Z08xQ0dIUjBpb1ZZNwphOGd1c1ZHU3I1M1ZHQ0xNS3Q1dXVCNFpUdFBDU3dzMW53SURBUUFCbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DCkFxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUIKQWY4d0hRWURWUjBPQkJZRUZHQVY0cVhwMFBMRDJpNnFOZWg5c2hqdkZGU25NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFBQWowQ0FRRk9ybGZPS01PRE9SMjFkTzZnUytScUNEUkpHVEp6ZkdUazR5SXJ3Q1JBQ0hYcUpiTUpvCmsvVE1JazVNT0FyWmd2N2U3a3Y0WVpMUVBlWFFMb3JyY2lDT2tQZzBSbXlsMXMwR2RIV0F1N1pGdm5LS3JyaTgKL1pIQkxrVERLT1YxR2R6ZXp3T1V4ZEdtWTloRTduRUl0elVRWWtZSjhhRUs5ejN6VmR5RTkySTRXMFJ2WUhCZgpIaUJkWDM4M1MvZExiZ1BRRTViRk9MTlhnQzNpWU5zNEdKSDVDUERXbEUyR2hrdmVuMzdZNUl0Z0FFL0FSTjZVCkg4NldmcjFxaFQxS2MrSDBhbnB1ODFzL0dzalhESmQ0MEp2RXltQVBGUnZBb0wrTnhaR2xFclMyWVhLQ0cxY2IKSFlOdnRHaS9JdG92VEFTNSs0NnJwemxnazhjMQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
                kafka.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZUVENDQkRXZ0F3SUJBZ0lRSlNkV0hJaXhXM2w3VElGZjBFRjJqREFOQmdrcWhraUc5dzBCQVFzRkFEQVQKTVJFd0R3WURWUVFERXdocllXWnJZUzFqWVRBZUZ3MHlNekE0TWpNeE1ERTJNak5hRncweU5EQTRNakl4TURFMgpNak5hTUJBeERqQU1CZ05WQkFNVEJXdGhabXRoTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCCkNnS0NBUUVBeU80anRZWTFtamx4KzdLbTdrRTdDM0QxSkd0R3ZiRFhJU29LU1FsOHRUYi9JTjBaZHBTM0c0YkIKOHJ2Y25TaXRHSVNxRFN3SHdyNWhvVG1RaDBtc2hBTFoyVVlwcENaL0prUDlZREo1Rk9QOWliVS9mTDRhZGg4eQovZVRHVm8wRGdRQnhwT3A5M3JXUk9yMXFzRGwxd0tyQXc1RmV0bnluSk5hUlQweTYzdWxVTTEzUzgzR1U4c05CCmozMzl6NjRJQVQzdEVjZ2hoRS9aaXZxWjV3UTJORTJWSzA3UTFmNy9MZDdNVGpFYSs3dUxTMTJ6ZEtCSDkxQkIKZmU5MzdlTmhMQXlEWGQ4ejU2SWg2NWUvMXNQTVlQcFNvekZQY1FrTjNZSXdMTGc0aWh0Z3BDMk1uY3l3SG9aQwpvK2ZiN1A5d3lLb0JxNHo1ZzNHL2N1VXhPMU5JdlFJREFRQUJvNElDbmpDQ0Fwb3dEZ1lEVlIwUEFRSC9CQVFECkFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUEKTUI4R0ExVWRJd1FZTUJhQUZHQVY0cVhwMFBMRDJpNnFOZWg5c2hqdkZGU25NSUlDT0FZRFZSMFJCSUlDTHpDQwpBaXVDSFd0aFptdGhMbXRoWm10aExuTjJZeTVqYkhWemRHVnlMbXh2WTJGc2dndHJZV1pyWVM1cllXWnJZWUlGCmEyRm1hMkdDUkd0aFptdGhMV052Ym5SeWIyeHNaWEl0TUM1cllXWnJZUzFqYjI1MGNtOXNiR1Z5TFdobFlXUnMKWlhOekxtdGhabXRoTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzZ2pKcllXWnJZUzFqYjI1MGNtOXNiR1Z5TFRBdQphMkZtYTJFdFkyOXVkSEp2Ykd4bGNpMW9aV0ZrYkdWemN5NXJZV1pyWVlJc2EyRm1hMkV0WTI5dWRISnZiR3hsCmNpMHdMbXRoWm10aExXTnZiblJ5YjJ4c1pYSXRhR1ZoWkd4bGMzT0NSR3RoWm10aExXTnZiblJ5YjJ4c1pYSXQKTVM1cllXWnJZUzFqYjI1MGNtOXNiR1Z5TFdobFlXUnNaWE56TG10aFptdGhMbk4yWXk1amJIVnpkR1Z5TG14dgpZMkZzZ2pKcllXWnJZUzFqYjI1MGNtOXNiR1Z5TFRFdWEyRm1hMkV0WTI5dWRISnZiR3hsY2kxb1pXRmtiR1Z6CmN5NXJZV1pyWVlJc2EyRm1hMkV0WTI5dWRISnZiR3hsY2kweExtdGhabXRoTFdOdmJuUnliMnhzWlhJdGFHVmgKWkd4bGMzT0NSR3RoWm10aExXTnZiblJ5YjJ4c1pYSXRNaTVyWVdacllTMWpiMjUwY205c2JHVnlMV2hsWVdScwpaWE56TG10aFptdGhMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNnakpyWVdacllTMWpiMjUwY205c2JHVnlMVEl1CmEyRm1hMkV0WTI5dWRISnZiR3hsY2kxb1pXRmtiR1Z6Y3k1cllXWnJZWUlzYTJGbWEyRXRZMjl1ZEhKdmJHeGwKY2kweUxtdGhabXRoTFdOdmJuUnliMnhzWlhJdGFHVmhaR3hsYzNNd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQgpBTWN2NVpXTEQrQWl0ZVBINlhOYTNXK3JCaHFhU0pGNWY1VFNtVTZ5QlY0Q0dBc2VjL1BXVXFHaDRKMlVUTVAxCmloQmtvWXcyWkJWaGlKMTR5N1FtUGthc01mQlN6bmNBamszOXZEa2NYTjVqWUNMb2hTN1RSZktRVUJ1S2w5VkYKa2VYZkxMVm1yR1M4YVpoOCthYk1zenRqSndoYkY0VUFOR3lQZlpkb2RCZFJYZDNMZStFNFlRajdRSEtObEpBZQpJNzdsbFExM3Z2UEdBYkhNWmVQbjVJaFBYTXVtTnp4YmdRNm9jN3BxWVV0RGRMa1oxNDlGV2xpaFJyTHFrTVVwCnNzd1F5SzRRYlJUYTh5U1NDY3VyT0ZiK05JZzlGaXpCaEtDQTAzYU1vT2JPOFA4bU5xOWVOTnpjelFyWERyVEcKTVRINEU3WGN5NzFVMVB1NWVsKy9NTXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                kafka.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeU80anRZWTFtamx4KzdLbTdrRTdDM0QxSkd0R3ZiRFhJU29LU1FsOHRUYi9JTjBaCmRwUzNHNGJCOHJ2Y25TaXRHSVNxRFN3SHdyNWhvVG1RaDBtc2hBTFoyVVlwcENaL0prUDlZREo1Rk9QOWliVS8KZkw0YWRoOHkvZVRHVm8wRGdRQnhwT3A5M3JXUk9yMXFzRGwxd0tyQXc1RmV0bnluSk5hUlQweTYzdWxVTTEzUwo4M0dVOHNOQmozMzl6NjRJQVQzdEVjZ2hoRS9aaXZxWjV3UTJORTJWSzA3UTFmNy9MZDdNVGpFYSs3dUxTMTJ6CmRLQkg5MUJCZmU5MzdlTmhMQXlEWGQ4ejU2SWg2NWUvMXNQTVlQcFNvekZQY1FrTjNZSXdMTGc0aWh0Z3BDMk0KbmN5d0hvWkNvK2ZiN1A5d3lLb0JxNHo1ZzNHL2N1VXhPMU5JdlFJREFRQUJBb0lCQVFDbG9ySXJMTlM1S3d2TQpha3h6OGJBRDBYMDBKWDd1Vm40eFo1K003OVl1NklST2loVTRqSVdabW0vOWNtSDk2QTh4UEFPVzBpb2ZucU9LCnJaSjRCQUxEM0RuTGc2eEdGam9ReUZGeDRJbXg3L1FNZGk0ODNkV2dkRDJyME5DemZwRlo0WXpOWDBTZHQ5MWQKcDlId0xaM2xVcDJQV2lIU20xV0o1NXRuM0ovYnF0VHhVM3RSNXRNR1RRTXAwM1BiT1RxUGpsQWlWYWRXcVpmeApvdkxpcmZ3dWhRaDRhcldBYVQ2UDdaS3JEVzhHMHA0ZC8wN01PUW1VRTRWcjZaelBSWkQzS0s1Rkw2THp6N0srCjFZSWk2bnVFeDNvd3Nta0hsZEV0SGlYTzFWN2NuM0hnc285bmhGQVE5aGdabEZ2dlc1ZHNQYklBU0s2dEZJZVYKK1BHOHlSamRBb0dCQU9jUy9pMjhPVFJYdUd6TFRxR1BwRWxGZjBkQXFIcU50cTZXRlRwMDhZL2g3UncxVDczRApiV0lMbFh0enJoSkRvQXhCUk5FT2loY0lZM2ovclh6clY0TVdJKzN5emt0VFErY25JUmhHWnN6VWtnUUl6V3BhCnVTb3ZtdGV4TDFlTTltTlRqTjJPcGc3eWlFN0JJRnVjL2h3YlBScXVidHpqT3IvUTM0WDd3Q09qQW9HQkFONmEKdkMrbWlaaXVWbVkyU29FVzBtQkxqMnBVc2ZUVnhsUDQ3d2w0bmcyOCtXUGtKbkZYTXNrL3ZaVXVNYkVZOUp5dApGM3VVU3dSMDdqbmdCZlZxRGF0ZXhsd2V6eDRzMWxTRG9TWmswOHFpK1BFZGoxREMzTHY5VXkrVEpDclBpZzBGCnhvZTF2WmVaUXh0VGlsTDY3VVRRUnQvUysrVWNNcXlCeGhrVVpLZ2ZBb0dCQU9RSTcwUHRJenJQY3BZUzBNZEoKZk9RK0xFd0J1QUl4aGQybkNNNEdpRGpveVZqMEYzeDZ0cUJ5TkJOL1pvSnBzREZIM0FTL1ozRXhleEQycUp2RgptRGdxQ2swUk41cElVcE4wSHduWXVDeGRmcmR5aEZ6M3FSSERwdmhDeUNpTFdMOU92WTRMN3o2REJCZE1LWVdmCldYb2RPMkR3VVVHMUVNNG83OTFHUXlnbkFvR0FiZmMwbGJtSWFaTmQvUm8remV4dk9zQzQ5VWNucmhKWTZpeWsKTVNLVHVhZXI3MnZLamQwTXFweEJWRXZBb29MNGU5bUtLek5EcDh6M3prRmIwRE4yMHp4N2N4Q0pNcGZsdlZSVgpMSGxNb3VMRlpaODdxQ0xMRmxiN1hCb3RHTFR6dHFFdXhPWEQ1ZnNCU3FPSFJwek16MXl3Vm11TW9rNit2YmRTCkhCdVY2Zk1DZ1lCbThrOW5EZHdVbHd0cnBHUUFxYjRtcG8vWGt6azJKV1BETGVCaHlSYW1tbEgwblVjUndMRy8KL1ZWU01hK1Z3aWdrdXdqRzFpRVozcyttMWdSdHVCNDlreGkyWmlQMGdhbVp4dGdxVmJucG9RbWNMaUdKT0hWQgo5R01PUnRUd2RSb3NTVnFqV2Y1cTlPbktGZjVPdXNQZCtRL1VKZVBFRHRJZmZ2cnZHSm9hOWc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
              type: Opaque


          controller:
            replicaCount: 3
            # resources:
            #   requests:
            #     memory: "2.5Gi"
            #     cpu: "1"
            #   limits:
            #     memory: "2.5Gi"
            #     cpu: "1"
          persistence:
            # storageClass: auto-resize
            size: 8Gi
          metrics:
            kafka:
              enabled: true
              certificatesSecret: kfka-tls
              tlsCaCert: kafka-ca.crt
              tlsCert: kafka.crt
              tlsKey: kafka.key
              resources:
                requests:
                  memory: "150Mi"
                  cpu: "0.1"
                limits:
                  memory: "150Mi"
                  cpu: "0.1"
            serviceMonitor:
              enabled: true
              labels:
                prometheus.io/scrap-with: kube-prometheus-stack

    - chart: console
      repoURL: https://helm.conduktor.io
      targetRevision: 1.0.1
      # https://github.com/conduktor/conduktor-public-charts/tree/main/charts/console
      helm:
        values: |
          fullnameOverride: conduktor-console
          config:
            organization:
              name: my-org
            admin:
              email: admin@conduktor.io
              password: password
            database:
              host: conduktor-postgres
              name: conduktor
              username: admin
              password: password
          ingress:
            enabled: true
            ingressClassName: nginx
            hostname: kafka.local.com.br

    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 12.8.3
      # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
      helm:
        values: |
          fullnameOverride: conduktor-postgres
          auth:
            postgresPassword: password
            database: conduktor
            username: admin
            password: password

  ignoreDifferences:
    - kind: Secret
      name: kafka-tls-passwords 
      namespace: kafka
      jsonPointers:
        - /data/keystore-password
        - /data/truststore-password

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kafka
