apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: <project-id>
      auth:
        workloadIdentity:
          clusterLocation: <cluster-region>
          clusterName: <cluster-name>
          clusterProjectID: <project-id>
          serviceAccountRef:
            name: external-secrets-op
            namespace: external-secrets
