apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:

    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: <infra-team>@<your-company>.com
    privateKeySecretRef:
      name: letsencrypt-staging

    solvers:
      - http01:
          ingress:
            class: nginx
